### ISSUE TITLE
How-to

### ISSUE THREAD

**Issue by xApep** [RhymeDigital/isotope_feeds#12]
Hello.
I'm struggling with setup for hours and just can't figure out how to properly setup so that .xml is generated.

The store config is in the attachment.
![isotope_feed](https://cloud.githubusercontent.com/assets/1315340/21076887/1a1fbeb4-bf38-11e6-9418-142bc0c8bc46.jpg)

Also Contao says that the file was generated but there is no such file in share folder.
![generated](https://cloud.githubusercontent.com/assets/1315340/21076891/29bc88b6-bf38-11e6-87e0-1a07920d84f0.jpg)

Can you please write just a quick info how to make things working :)

Thanks.

**Comment by bytehead** [comment]
You'll find two buttons (`Refresh feed` and `Regenerate feed`) on the product list view:  

<img width="724" alt="bildschirmfoto 2016-12-12 um 08 43 38" src="https://cloud.githubusercontent.com/assets/754921/21091538/2a6d9fe2-c047-11e6-8829-4a7c02e1313a.png">

Click them in order `Refresh feed` to build the product cache and then `Regenerate feed` to acutally write the xml file.

**Comment by xApep** [comment]
I did that, and as you can see in the system log screen shot the xml file is generated. But when i look into share folder there is no file except for contao sitemap.

Thas why is strange to me, cause there is no error even system says that the file us generated but no file exist so I tought that there is something wrong with my settings.

Im using contao 3.5.9 and isotope 2.2.2

**Comment by bytehead** [comment]
Hmm. Don't know. Have you tried it with isotope `2.3.x`?
Does it generate some cache files in `isotope/cache/*/**`?

**Comment by xApep** [comment]
Ok i will try with 2.3 version.

No cache file is there -  there isn't even folder cache in root isotope/

**Comment by xApep** [comment]
But those settings are correct or there is something else to be setup? What exactly does Feed base link means?

Thanks.

**Comment by bytehead** [comment]
You need to enable the feed in the isotope shop configuration:
<img width="785" alt="bildschirmfoto 2016-12-12 um 17 53 05" src="https://cloud.githubusercontent.com/assets/754921/21108026/e8494592-c093-11e6-87a5-654afeed0da9.png">

**Comment by xApep** [comment]
I did that yes. 
The feed base link let say is http://localhost/isotope_latest/ or http://dev.domain.com/isotope_latest (tested on both servers).
The feed reader page is Product reader page.

I'm checking only the RSS 2.0 (but Google base also isn't working).

Than I go to product management and I click those feed icons but file isn't created. Also the cache folder isn't created.

I have tested also with Isotope 2.4.0

**Comment by bytehead** [comment]
Require  `"rhymedigital/isotope-feeds": "dev-develop"` and try again. There is a merge missing (#10) in master.

**Comment by xApep** [comment]
Updated the files but there is no effects. Damn :)

**Comment by bytehead** [comment]
Sorry, can't help then.

**Comment by xApep** [comment]
First issue was that I had to manually create folders in isotope "/cache1/rss20" then the file in share was created - but it had no items (just channel information).

After debugging and little luck I figure out that you must check Use in feed so that xml in generated in cache folder.

**Comment by blairwinans** [comment]
Hi there - sorry for the (very) late reply on this but let us know if there are any additional questions.

**Comment by cmichael-de** [comment]
> First issue was that I had to manually create folders in isotope "/cache1/rss20" then the file in share was created - but it had no items (just channel information).
> 
> After debugging and little luck I figure out that you must check Use in feed so that xml in generated in cache folder.

In my case the "Use in Feed" checkbox was hidden. After setting the group from "hidden" to "Meta-Angaben" in all my producttypes I was able to check the "Use in Feed" on the product edit page. There are more fields provided by this extension as you can see in the screenshot:

![image](https://user-images.githubusercontent.com/6968063/179786527-33c378d0-59b3-404a-b274-6153bbff4342.png)
