### ISSUE TITLE
Refresh Feed

### ISSUE THREAD

**Issue by d0p3fish** [RhymeDigital/isotope_feeds#29]
If i click on refresh feed, i got
"Rhyme\IsotopeFeedsBundle\Controller\FeedController" has no container set, did you forget to define it as a service subscriber?

var/cache were already deleted.
contao 4.12.2  isotope 2.7.4

**Comment by FlorianEisenmenger** [comment]
Up!
Have the same issues under Contao 4.13.6
"Rhyme\IsotopeFeedsBundle\Controller\FeedController" has no container set, did you forget to define it as a service subscriber?

Also the URL to the products is not correct. It is like https://www.myshop.detest/name-of-product where it should be https://www.myshop.de/shop/category/name-of-product

Any ideas?

**Comment by bytehead** [comment]
@blairwinans this was possibly solved by #31.
