### ISSUE TITLE
Installation Problem with Contao 3.5.0 and Isotope 2.2.6

### ISSUE THREAD

**Issue by dengelstein** [RhymeDigital/isotope_feeds#3]
After install the package I cant get into "Products" I get following Error

Warning: in_array() expects parameter 2 to be array, null given in system/modules/core/library/Contao/System.php on line 140
#0 [internal function]: __error(2, 'in_array() expe...', '/www/htdocs/w01...', 140, Array)
#1 system/modules/core/library/Contao/System.php(140): in_array('getInstance', NULL)
#2 system/modules/core/drivers/DC_Table.php(206): Contao\System->import('Rhyme\Backend\I...')
#3 system/modules/isotope/drivers/DC_ProductData.php(93): Contao\DC_Table->__construct('tl_iso_product')
#4 system/modules/core/classes/Backend.php(408): DC_ProductData->__construct('tl_iso_product', Array)
#5 system/modules/core/controllers/BackendMain.php(131): Contao\Backend->getBackendModule('iso_products')
#6 contao/main.php(20): Contao\BackendMain->run()
#7 {main}

Fatal error: Class 'Rhyme\Backend\IsotopeProduct\FeedCallbacks' not found in /www/htdocs/w0123444/industrie.center/system/modules/core/library/Contao/System.php on line 140

**Comment by schaffen** [comment]
Hello.

I´ve got the same issue with version Contao 3.5.0 and Isotope 2.2.5.

Errors and Warnings are the same as above.
Just wanted to let you know :)

Regards
Martin

**Comment by bytehead** [comment]
It's actually fixed in the [develop](https://github.com/RhymeDigital/isotope_feeds/tree/develop)-branch.
