### ISSUE TITLE
Missing installation guide

### ISSUE THREAD

**Issue by d0p3fish** [RhymeDigital/isotope_feeds#30]
Im not a contao user. I just want a product export as csv or something.
How to use this plugin?

**Comment by operatorone** [comment]
How much would you charge for a comprehensive installation guide?
Or I can offer you to create the German translation in exchange. What do you think?
Or you explain it to me and I create an installation video?

**Comment by blairwinans** [comment]
@operatorone Let me see if I can add in a guide in the README. It may take me a few days to get to it.

**Comment by operatorone** [comment]
Hi @blairwinans , that would be awesome and if you like, I can do the translation anyway 😎

**Comment by blairwinans** [comment]
@operatorone I just pushed it in the latest minor release—feedback is welcome and a translation would be great. While this may not fully address the CSV issue noted by @d0p3fish, this should give you an idea of what is possible. Since this extension is not intended to do a CSV export out of the box and is more for Feeds, I am going to close this issue.

**Comment by operatorone** [comment]
Hi @blairwinans thanks a lot for the great guide, you're awesome.

I have just one question about _You should also set the default Reader page for your products, which will be used to generate the product URL in the feed._ You can define a reader page, but the products in one of the stores I work on, has the reader in the category page, so the products have no common reader page.

1. Do you think this might be a problem to use a general reader page and have maybe two or more links with the same content on the reader pages? Or may be set the common reader page to "noindex, follow"? 
2. Or you create the possibility to add a link or a reader page per product. So a specific link can be defined separately and if it's not used in the products the common link is used. How about that? 

I already translated your guide and will have a look at the xlif files later on.

Cheers
operatorone


### Anleitung

Erweiterung zum Erstellen von Produkt-Feeds in Isotope eCommerce für Contao Open Source CMS

Standardmäßig wird diese Erweiterung mit zwei Feed-Typen ausgeliefert: 
* RSS 2.0 
* Google Merchant (früher bekannt als Google Base oder auch Google Shopping)

Hinweis: Um einen richtig formatierten Google Merchant Feed zu erzeugen, müssen Sie die zusätzlichen Informationen zu Ihren Produkten im Abschnitt Produktverwaltung ausfüllen. 

# Abhängigkeiten 
Programmiert für 
* https://github.com/isotope/core 
 
# Installation 
Installiere das Bundle über Composer: 

		composer require rhymedigital/isotope-feeds 

oder über den Contao Manager, indem du nach „Isotope Feeds“ suchst. 

Stelle sicher, dass du nach der Installation Contao Install oder die Datenbankaktualisierung im Manager ausführst.
# Konfiguration
Damit Ihr Produkt-Feed funktioniert, musst du einige Einstellungen vornehmen, um dem System mitzuteilen, welche Feed-Typen du verwenden möchtest und welche Produkte im Feed beinhaltet sein sollen. 

Bei dieser Konfiguration wird vorausgesetzt, dass du bereits deinen Isotope-Shop mithilfe des Konfigurationsleitfadens installiert und eingerichtet hast. 

## Konfiguration des Shops
1. Melde dich bei deinem Contao-Backend an und gehen zu Isotope eCommerce > Shop-Konfiguration > Konfigurationen und bearbeite deine Shop-Konfiguration. 
1. Im einen neuen Abschnitt namens "Feeds" findest du ein Kontrollkästchen für "Produkt-Feeds hinzufügen". Aktiviere das Kontrollkästchen. 
1. Wähle hier den Feed-Typ aus. Wähle für Google Merchant-Feeds „Google Base“ aus. Du solltest ein Präfix für die Feed-Datei eingeben, dass den Namen des Feeds definiert, (d. h. _products_ gibt dann eine Datei namens products.xml aus). Optional kannst du auch einen Feed Base Link hinzufügen (standardmäßig wird der Base Link deiner Contao Umgebung verwendet, sprich deine Domain). Anschließend kannst du noch einen Titel und eine Beschreibung festlegen. Du solltest auch die Standard-Produkt-Reader-Seite für deine Produkte festlegen, die zum Generieren der Produkt-URL im Feed verwendet wird. 
## Produkttypen-Konfiguration
Der nächste Schritt besteht darin, die Felder zu aktivieren, die Teil des Google Merchant-Feeds in deinen Produkttypen werden sollen. Ohne die Einstellung „Im Feed ausgeben“ für ein Produkt festzulegen, wird es nicht im Feed angezeigt. Daher musst du die Feed-Felder zu deinen Produktfeldern hinzufügen. 

1. Gehe zu Shop-Konfiguration > Produkttypen und bearbeite jeden deiner Produkttypen. 
1. Standardmäßig werden die Felder „Im Feed ausgeben“, „Zustand“, „Verfügbarkeit“, „Marke“, „GTIN“ und „MPN“ aktiviert, und wenn du den Produkttyp speicherst, werden diese für deine Produkte aktiviert. Es gibt auch weitere Felder, die du dem Feed hinzufügen kannst. Diese sind jedoch nicht zwingend erforderlich.
1. Wenn du deine Produkttypen speicherst, werden diese Feed-Felder jedem Produkt dieses Typs hinzugefügt.
## Produktkonfiguration
Um im Feed angezeigt zu werden, musst du die Option „Im Feed ausgeben“ jeweils für jedes Produkt aktivieren. Dies gilt auch für Variantenprodukte! 

1. Bearbeite im Bereich Produkte deine Produkte und/oder Produktvarianten und vergewissere dich, dass das Kontrollkästchen „Im Feed ausgeben“ aktiviert ist.
1. Wenn du den Google Merchant-Feed einrichtest, musst du sicherstellen, dass du das Minimum an erforderlichen Informationen ausgefüllt hast, nämlich 2 der 3 Felder für Marke, GTIN oder MPN. 

Für jedes aktivierte Produkt/Variante, wird eine Cache-Datei im Ordner root/isotope/cache erzeugt. Diese zwischengespeicherten XML-Dateien werden dann zu einer einzigen Feed-XML-Datei zusammengesetzt, die im public/share-Verzeichnis (oder web/share bei älteren Contao 4-Installationen) abgelegt wird. 

Die Feed-Datei wird täglich über den Hook _generateFeeds_ generiert, oder du kannst sie manuell erstellen, indem du in der Produktverwaltung auf die Schaltfläche „Feed neu generieren“ klickst. 

Du kannst auch eine Neugenerierung aller zwischengespeicherten Produkt-/Varianten-Dateien durchführen, indem du auf die Schaltfläche „Feed-Cache aktualisieren“ klickst. Denke daran, dass du danach auch auf die Schaltfläche „Feed regenerieren“ klicken musst.

# # Anpassung
Möglicherweise musst du einen völlig anderen Feedtyp als die beiden bereitgestellten erstellen. Alle bereitgestellten Feeds werden ausgehend von der Basisklasse _Contao\Feed_ als Ausgangspunkt erweitert, und jede einzelne Produkt-/Varianten-XML wird ausgehend von der Basisklasse _Contao\FeedItem_ erweitert. Es steht dir frei, sowohl deinen eigenen Feed als auch benutzerdefinierte FeedItem-Klassen zu erstellen. Um sie mit Isotope Feeds zu verwenden, müssen Sie sie nur in Ihrer config.php-Datei für Contao registrieren, indem du sie in das Array _$GLOBALS['ISO_FEEDS‘]_ einfügst. Nachfolgend findest du ein Beispiel für die anfängliche Konfiguration der beiden enthaltenen Feeds.
