### ISSUE TITLE
Additional link option within product

### ISSUE THREAD

**Issue by operatorone** [RhymeDigital/isotope_feeds#38]
I have the product reader integrated in the category page and have no solitary product reader page. 

Would it be possible to add an option in the products to choose a specific reader page per product? So, a specific link can be defined separately and if it's not used in the products the common link is used. 

Can you add this? Please let me know how much this might cost, and I'll sponsor the work on it.

**Comment by blairwinans** [comment]
@operatorone let me see what I can come up with. Unfortunately right now I am up against some other deadlines but I'll see if we can get to this within the next week or so.

**Comment by operatorone** [comment]
@blairwinans thank you so much for your answer and it would be wonderful if you can have a look at it

**Comment by blairwinans** [comment]
@operatorone I added it in cab5d32ea86a9376d9588eaadba738d67b81e7af and will bump the release, so let me know if that does what you need.

**Comment by operatorone** [comment]
Hi @blairwinans thanks a lot for your efforts. I will test it and will get back to you.

**Comment by operatorone** [comment]
Hi @blairwinans, thank you for your patience. I just checked the new option and it works like a charm. Awesome!

**Comment by operatorone** [comment]
Just a hint, if I set it in the product type to "standard" in the mandatory option, it doesn't appear on the product page in the backend. If set to "no" it appears. https://share.cleanshot.com/QNsbz9Y80RLJnjhC02Sj
