### ISSUE TITLE
Error during cron "Call to a member function getLocale() on null" in Helper/IsotopeFeeds.php:253

### ISSUE THREAD

**Issue by michb** [RhymeDigital/isotope_feeds#39]
I noticed not all of my daily crons where executed. So i found following error in the logs:
```
[2023-03-07 12:18:12] request.CRITICAL: Uncaught PHP Exception Error: "Call to a member function getLocale() on null" at 
/var/www/html/.../vendor/rhymedigital/isotope-feeds/src/Helper/IsotopeFeeds.php line 253 {"exception":"
[object] (Error(code: 0): Call to a member function getLocale() on null at 
/var/www/html/.../vendor/rhymedigital/isotope-feeds/src/Helper/IsotopeFeeds.php:253)"} []
```
Then I digged deeper and found that if you check this in the "https://domain.local/_contao/cron" route there will be no error but if try to log the result in a real cron execution you recieve the above error. 

Short fix for now is setting the feedLanguage in the database.

**Comment by blairwinans** [comment]
@michb I added a check for no request stack in 2c50180c500b17ca11264b015c6c8c786fc9f6f8, and if nothing is set up in the config, I am defaulting to 'en' when nothing is available.
